spring.application.name=cynapse
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false
spring.datasource.url=${DATABASE_URL:jdbc:mariadb://localhost:3306/cynapse}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:mypass}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=${SERVER_PORT:8080}